grades = [[5, 3, 3, 5, 4], [2, 2, 2, 3], [4, 5, 5, 2], [4, 4, 3], [5, 5, 5, 4, 5]]
students = sorted({'Johnny', 'Bilbo', 'Steve', 'Khendrik', 'Aaron'})
marks = dict(zip(students,grades))
a = (sum(marks['Aaron']))
marks.update({'Aaron': a/5})
b = (sum(marks['Bilbo']))
marks.update({'Bilbo': b/4})
c = (sum(marks['Johnny']))
marks.update({'Johnny': c/4})
d = (sum(marks['Khendrik']))
marks.update({'Khendrik': d/3})
e = (sum(marks['Steve']))
marks.update({'Steve': e/5})
print(marks)
